---
kind: Pod
apiVersion: v1
metadata:
  name: hello-app
  namespace: production
  labels:
    app: hello-app
spec:
  containers:
  - name: hello-app
    image: hashicorp/http-echo:0.2.3
    args:
    - "-text=Hello World! This is a hello-world app"

---
kind: Service
apiVersion: v1
metadata:
  name: hello-service
  namespace: production
spec:
  selector:
    app: hello-app
  ports:
  - protocol: TCP
    port: 5678
    targetPort: 5678
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ingress
  namespace: production
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/hello"
        backend:
          service:
            name: hello-service
            port:
              number: 5678
