---
- name: Install packages with apt
  hosts: all
  become: yes

  vars:
    # Packages to be installed
    - packages:
      - curl
      - wget
      - vim
      - neofetch
      - tmux
      - screen
      - tree
      - iputils-ping
  roles:
    - role: apt.ops/install-packages.ops/
