---
servers:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

  hosts:
    ubuntu-server:
      ansible_host: "xxx.xxx.xxx.xxx"

remote:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

  hosts:
    vps:
      ansible_host: "xxx.xxx.xxx.xxx"
